<?php

?>
<script>
RateItCoolAPI.init({
    username: '<?php echo Mage::getStoreConfig('catalog/RateItCool_ProductReviews/api_user'); ?>',
    password: '<?php echo Mage::getStoreConfig('catalog/RateItCool_ProductReviews/api_key'); ?>',
    limit: '<?php echo Mage::getStoreConfig('catalog/RateItCool_ProductReviews/limit'); ?>',
    securitytext: '<?php echo Mage::getStoreConfig('catalog/RateItCool_ProductReviews/security_text'); ?>',
    noConflict: false
  });
</script>
